image: node:lts

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
    - yarn --frozen-lockfile --non-interactive
    - yarn build
  artifacts:
    paths:
      - dist/
      - docs/
    expire_in: 1 week

npm:
  stage: deploy
  only:
    - master
  script:
    - yarn semantic-release
  artifacts:
    paths:
      - docs/
      - dist/
    expire_in: 1 week

pages:
  stage: deploy
  only:
    refs:
      - master
  script:
    - cp -R docs/ public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week
