image: node:lts

.except_release_commits:
  except: &except_release_definition
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore(release).*/

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  except: *except_release_definition
  script:
    - yarn --frozen-lockfile --non-interactive
    - yarn build
  artifacts:
    paths:
      - dist/
      - docs/
    expire_in: 1 week

npm:
  stage: deploy
  only:
    - master
  except: *except_release_definition
  script:
    - yarn semantic-release
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - cp -R docs/ public/
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    <<: *except_release_definition
    refs:
      - master
