image: node:lts

.except_release_commits:
  except: &except_release_definition
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore(release).*/

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - yarn --frozen-lockfile --non-interactive

build:
  stage: build
  only:
    - merge_requests
    - master@spartanbio-ux/schedio
  except: *except_release_definition
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - yarn docs
  artifacts:
    paths:
      - docs/
    expire_in: 1 week
  only:
    - master
