image: node:lts

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
    - yarn --frozen-lockfile --non-interactive
    - yarn build
  artifacts:
    paths:
      - dist/
      - public/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "publish"
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - master
